# Generated by gallery/generate.py; do not edit.
setblock 2048 100 2060 botanypots:gray_glazed_terracotta_botany_pot[facing=south,level=6,waterlogged=false]
data merge block 2048 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2052 100 2060 botanypots:gray_glazed_terracotta_hopper_botany_pot[facing=east,level=6,waterlogged=false]
data merge block 2052 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2056 100 2060 botanypots:gray_glazed_terracotta_waxed_botany_pot[facing=north,level=6,waterlogged=false]
data merge block 2056 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2060 100 2060 botanypots:gray_terracotta_botany_pot[facing=west,level=6,waterlogged=false]
data merge block 2060 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2063 100 2060 minecraft:barrier
setblock 2065 100 2060 minecraft:barrier
setblock 2064 100 2059 minecraft:barrier
setblock 2064 100 2061 minecraft:barrier
setblock 2064 100 2060 botanypots:gray_terracotta_hopper_botany_pot[facing=south,level=6,waterlogged=true]
data merge block 2064 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2067 100 2060 minecraft:barrier
setblock 2069 100 2060 minecraft:barrier
setblock 2068 100 2059 minecraft:barrier
setblock 2068 100 2061 minecraft:barrier
setblock 2068 100 2060 botanypots:gray_terracotta_waxed_botany_pot[facing=east,level=6,waterlogged=true]
data merge block 2068 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2071 100 2060 minecraft:barrier
setblock 2073 100 2060 minecraft:barrier
setblock 2072 100 2059 minecraft:barrier
setblock 2072 100 2061 minecraft:barrier
setblock 2072 100 2060 botanypots:green_concrete_botany_pot[facing=north,level=6,waterlogged=true]
data merge block 2072 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2075 100 2060 minecraft:barrier
setblock 2077 100 2060 minecraft:barrier
setblock 2076 100 2059 minecraft:barrier
setblock 2076 100 2061 minecraft:barrier
setblock 2076 100 2060 botanypots:green_concrete_hopper_botany_pot[facing=west,level=6,waterlogged=true]
data merge block 2076 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2080 100 2060 botanypots:green_concrete_waxed_botany_pot[facing=south,level=7,waterlogged=false]
data merge block 2080 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2084 100 2060 botanypots:green_glazed_terracotta_botany_pot[facing=east,level=7,waterlogged=false]
data merge block 2084 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2088 100 2060 botanypots:green_glazed_terracotta_hopper_botany_pot[facing=north,level=7,waterlogged=false]
data merge block 2088 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2092 100 2060 botanypots:green_glazed_terracotta_waxed_botany_pot[facing=west,level=7,waterlogged=false]
data merge block 2092 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2095 100 2060 minecraft:barrier
setblock 2097 100 2060 minecraft:barrier
setblock 2096 100 2059 minecraft:barrier
setblock 2096 100 2061 minecraft:barrier
setblock 2096 100 2060 botanypots:green_terracotta_botany_pot[facing=south,level=7,waterlogged=true]
data merge block 2096 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2099 100 2060 minecraft:barrier
setblock 2101 100 2060 minecraft:barrier
setblock 2100 100 2059 minecraft:barrier
setblock 2100 100 2061 minecraft:barrier
setblock 2100 100 2060 botanypots:green_terracotta_hopper_botany_pot[facing=east,level=7,waterlogged=true]
data merge block 2100 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2103 100 2060 minecraft:barrier
setblock 2105 100 2060 minecraft:barrier
setblock 2104 100 2059 minecraft:barrier
setblock 2104 100 2061 minecraft:barrier
setblock 2104 100 2060 botanypots:green_terracotta_waxed_botany_pot[facing=north,level=7,waterlogged=true]
data merge block 2104 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2107 100 2060 minecraft:barrier
setblock 2109 100 2060 minecraft:barrier
setblock 2108 100 2059 minecraft:barrier
setblock 2108 100 2061 minecraft:barrier
setblock 2108 100 2060 botanypots:light_blue_concrete_botany_pot[facing=west,level=7,waterlogged=true]
data merge block 2108 100 2060 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2048 100 2064 botanypots:light_blue_concrete_hopper_botany_pot[facing=south,level=8,waterlogged=false]
data merge block 2048 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2052 100 2064 botanypots:light_blue_concrete_waxed_botany_pot[facing=east,level=8,waterlogged=false]
data merge block 2052 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2056 100 2064 botanypots:light_blue_glazed_terracotta_botany_pot[facing=north,level=8,waterlogged=false]
data merge block 2056 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2060 100 2064 botanypots:light_blue_glazed_terracotta_hopper_botany_pot[facing=west,level=8,waterlogged=false]
data merge block 2060 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2063 100 2064 minecraft:barrier
setblock 2065 100 2064 minecraft:barrier
setblock 2064 100 2063 minecraft:barrier
setblock 2064 100 2065 minecraft:barrier
setblock 2064 100 2064 botanypots:light_blue_glazed_terracotta_waxed_botany_pot[facing=south,level=8,waterlogged=true]
data merge block 2064 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2067 100 2064 minecraft:barrier
setblock 2069 100 2064 minecraft:barrier
setblock 2068 100 2063 minecraft:barrier
setblock 2068 100 2065 minecraft:barrier
setblock 2068 100 2064 botanypots:light_blue_terracotta_botany_pot[facing=east,level=8,waterlogged=true]
data merge block 2068 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2071 100 2064 minecraft:barrier
setblock 2073 100 2064 minecraft:barrier
setblock 2072 100 2063 minecraft:barrier
setblock 2072 100 2065 minecraft:barrier
setblock 2072 100 2064 botanypots:light_blue_terracotta_hopper_botany_pot[facing=north,level=8,waterlogged=true]
data merge block 2072 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2075 100 2064 minecraft:barrier
setblock 2077 100 2064 minecraft:barrier
setblock 2076 100 2063 minecraft:barrier
setblock 2076 100 2065 minecraft:barrier
setblock 2076 100 2064 botanypots:light_blue_terracotta_waxed_botany_pot[facing=west,level=8,waterlogged=true]
data merge block 2076 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2080 100 2064 botanypots:light_gray_concrete_botany_pot[facing=south,level=9,waterlogged=false]
data merge block 2080 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2084 100 2064 botanypots:light_gray_concrete_hopper_botany_pot[facing=east,level=9,waterlogged=false]
data merge block 2084 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2088 100 2064 botanypots:light_gray_concrete_waxed_botany_pot[facing=north,level=9,waterlogged=false]
data merge block 2088 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2092 100 2064 botanypots:light_gray_glazed_terracotta_botany_pot[facing=west,level=9,waterlogged=false]
data merge block 2092 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2095 100 2064 minecraft:barrier
setblock 2097 100 2064 minecraft:barrier
setblock 2096 100 2063 minecraft:barrier
setblock 2096 100 2065 minecraft:barrier
setblock 2096 100 2064 botanypots:light_gray_glazed_terracotta_hopper_botany_pot[facing=south,level=9,waterlogged=true]
data merge block 2096 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2099 100 2064 minecraft:barrier
setblock 2101 100 2064 minecraft:barrier
setblock 2100 100 2063 minecraft:barrier
setblock 2100 100 2065 minecraft:barrier
setblock 2100 100 2064 botanypots:light_gray_glazed_terracotta_waxed_botany_pot[facing=east,level=9,waterlogged=true]
data merge block 2100 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2103 100 2064 minecraft:barrier
setblock 2105 100 2064 minecraft:barrier
setblock 2104 100 2063 minecraft:barrier
setblock 2104 100 2065 minecraft:barrier
setblock 2104 100 2064 botanypots:light_gray_terracotta_botany_pot[facing=north,level=9,waterlogged=true]
data merge block 2104 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2107 100 2064 minecraft:barrier
setblock 2109 100 2064 minecraft:barrier
setblock 2108 100 2063 minecraft:barrier
setblock 2108 100 2065 minecraft:barrier
setblock 2108 100 2064 botanypots:light_gray_terracotta_hopper_botany_pot[facing=west,level=9,waterlogged=true]
data merge block 2108 100 2064 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2048 100 2068 botanypots:light_gray_terracotta_waxed_botany_pot[facing=south,level=10,waterlogged=false]
data merge block 2048 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2052 100 2068 botanypots:lime_concrete_botany_pot[facing=east,level=10,waterlogged=false]
data merge block 2052 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2056 100 2068 botanypots:lime_concrete_hopper_botany_pot[facing=north,level=10,waterlogged=false]
data merge block 2056 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2060 100 2068 botanypots:lime_concrete_waxed_botany_pot[facing=west,level=10,waterlogged=false]
data merge block 2060 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2063 100 2068 minecraft:barrier
setblock 2065 100 2068 minecraft:barrier
setblock 2064 100 2067 minecraft:barrier
setblock 2064 100 2069 minecraft:barrier
setblock 2064 100 2068 botanypots:lime_glazed_terracotta_botany_pot[facing=south,level=10,waterlogged=true]
data merge block 2064 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2067 100 2068 minecraft:barrier
setblock 2069 100 2068 minecraft:barrier
setblock 2068 100 2067 minecraft:barrier
setblock 2068 100 2069 minecraft:barrier
setblock 2068 100 2068 botanypots:lime_glazed_terracotta_hopper_botany_pot[facing=east,level=10,waterlogged=true]
data merge block 2068 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2071 100 2068 minecraft:barrier
setblock 2073 100 2068 minecraft:barrier
setblock 2072 100 2067 minecraft:barrier
setblock 2072 100 2069 minecraft:barrier
setblock 2072 100 2068 botanypots:lime_glazed_terracotta_waxed_botany_pot[facing=north,level=10,waterlogged=true]
data merge block 2072 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2075 100 2068 minecraft:barrier
setblock 2077 100 2068 minecraft:barrier
setblock 2076 100 2067 minecraft:barrier
setblock 2076 100 2069 minecraft:barrier
setblock 2076 100 2068 botanypots:lime_terracotta_botany_pot[facing=west,level=10,waterlogged=true]
data merge block 2076 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2080 100 2068 botanypots:lime_terracotta_hopper_botany_pot[facing=south,level=11,waterlogged=false]
data merge block 2080 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2084 100 2068 botanypots:lime_terracotta_waxed_botany_pot[facing=east,level=11,waterlogged=false]
data merge block 2084 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2088 100 2068 botanypots:magenta_concrete_botany_pot[facing=north,level=11,waterlogged=false]
data merge block 2088 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2092 100 2068 botanypots:magenta_concrete_hopper_botany_pot[facing=west,level=11,waterlogged=false]
data merge block 2092 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2095 100 2068 minecraft:barrier
setblock 2097 100 2068 minecraft:barrier
setblock 2096 100 2067 minecraft:barrier
setblock 2096 100 2069 minecraft:barrier
setblock 2096 100 2068 botanypots:magenta_concrete_waxed_botany_pot[facing=south,level=11,waterlogged=true]
data merge block 2096 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2099 100 2068 minecraft:barrier
setblock 2101 100 2068 minecraft:barrier
setblock 2100 100 2067 minecraft:barrier
setblock 2100 100 2069 minecraft:barrier
setblock 2100 100 2068 botanypots:magenta_glazed_terracotta_botany_pot[facing=east,level=11,waterlogged=true]
data merge block 2100 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2103 100 2068 minecraft:barrier
setblock 2105 100 2068 minecraft:barrier
setblock 2104 100 2067 minecraft:barrier
setblock 2104 100 2069 minecraft:barrier
setblock 2104 100 2068 botanypots:magenta_glazed_terracotta_hopper_botany_pot[facing=north,level=11,waterlogged=true]
data merge block 2104 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2107 100 2068 minecraft:barrier
setblock 2109 100 2068 minecraft:barrier
setblock 2108 100 2067 minecraft:barrier
setblock 2108 100 2069 minecraft:barrier
setblock 2108 100 2068 botanypots:magenta_glazed_terracotta_waxed_botany_pot[facing=west,level=11,waterlogged=true]
data merge block 2108 100 2068 {Items:[]}
scoreboard players add #shells botany_gallery 1
