# Generated by gallery/generate.py; do not edit.
setblock 2048 100 2084 botanypots:red_concrete_botany_pot[facing=south,level=2,waterlogged=false]
data merge block 2048 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2052 100 2084 botanypots:red_concrete_hopper_botany_pot[facing=east,level=2,waterlogged=false]
data merge block 2052 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2056 100 2084 botanypots:red_concrete_waxed_botany_pot[facing=north,level=2,waterlogged=false]
data merge block 2056 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2060 100 2084 botanypots:red_glazed_terracotta_botany_pot[facing=west,level=2,waterlogged=false]
data merge block 2060 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2063 100 2084 minecraft:barrier
setblock 2065 100 2084 minecraft:barrier
setblock 2064 100 2083 minecraft:barrier
setblock 2064 100 2085 minecraft:barrier
setblock 2064 100 2084 botanypots:red_glazed_terracotta_hopper_botany_pot[facing=south,level=2,waterlogged=true]
data merge block 2064 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2067 100 2084 minecraft:barrier
setblock 2069 100 2084 minecraft:barrier
setblock 2068 100 2083 minecraft:barrier
setblock 2068 100 2085 minecraft:barrier
setblock 2068 100 2084 botanypots:red_glazed_terracotta_waxed_botany_pot[facing=east,level=2,waterlogged=true]
data merge block 2068 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2071 100 2084 minecraft:barrier
setblock 2073 100 2084 minecraft:barrier
setblock 2072 100 2083 minecraft:barrier
setblock 2072 100 2085 minecraft:barrier
setblock 2072 100 2084 botanypots:red_nether_bricks_botany_pot[facing=north,level=2,waterlogged=true]
data merge block 2072 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2075 100 2084 minecraft:barrier
setblock 2077 100 2084 minecraft:barrier
setblock 2076 100 2083 minecraft:barrier
setblock 2076 100 2085 minecraft:barrier
setblock 2076 100 2084 botanypots:red_nether_bricks_hopper_botany_pot[facing=west,level=2,waterlogged=true]
data merge block 2076 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2080 100 2084 botanypots:red_nether_bricks_waxed_botany_pot[facing=south,level=3,waterlogged=false]
data merge block 2080 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2084 100 2084 botanypots:red_terracotta_botany_pot[facing=east,level=3,waterlogged=false]
data merge block 2084 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2088 100 2084 botanypots:red_terracotta_hopper_botany_pot[facing=north,level=3,waterlogged=false]
data merge block 2088 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2092 100 2084 botanypots:red_terracotta_waxed_botany_pot[facing=west,level=3,waterlogged=false]
data merge block 2092 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2095 100 2084 minecraft:barrier
setblock 2097 100 2084 minecraft:barrier
setblock 2096 100 2083 minecraft:barrier
setblock 2096 100 2085 minecraft:barrier
setblock 2096 100 2084 botanypots:stone_bricks_botany_pot[facing=south,level=3,waterlogged=true]
data merge block 2096 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2099 100 2084 minecraft:barrier
setblock 2101 100 2084 minecraft:barrier
setblock 2100 100 2083 minecraft:barrier
setblock 2100 100 2085 minecraft:barrier
setblock 2100 100 2084 botanypots:stone_bricks_hopper_botany_pot[facing=east,level=3,waterlogged=true]
data merge block 2100 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2103 100 2084 minecraft:barrier
setblock 2105 100 2084 minecraft:barrier
setblock 2104 100 2083 minecraft:barrier
setblock 2104 100 2085 minecraft:barrier
setblock 2104 100 2084 botanypots:stone_bricks_waxed_botany_pot[facing=north,level=3,waterlogged=true]
data merge block 2104 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2107 100 2084 minecraft:barrier
setblock 2109 100 2084 minecraft:barrier
setblock 2108 100 2083 minecraft:barrier
setblock 2108 100 2085 minecraft:barrier
setblock 2108 100 2084 botanypots:terracotta_botany_pot[facing=west,level=3,waterlogged=true]
data merge block 2108 100 2084 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2048 100 2088 botanypots:terracotta_hopper_botany_pot[facing=south,level=4,waterlogged=false]
data merge block 2048 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2052 100 2088 botanypots:terracotta_waxed_botany_pot[facing=east,level=4,waterlogged=false]
data merge block 2052 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2056 100 2088 botanypots:tuff_bricks_botany_pot[facing=north,level=4,waterlogged=false]
data merge block 2056 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2060 100 2088 botanypots:tuff_bricks_hopper_botany_pot[facing=west,level=4,waterlogged=false]
data merge block 2060 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2063 100 2088 minecraft:barrier
setblock 2065 100 2088 minecraft:barrier
setblock 2064 100 2087 minecraft:barrier
setblock 2064 100 2089 minecraft:barrier
setblock 2064 100 2088 botanypots:tuff_bricks_waxed_botany_pot[facing=south,level=4,waterlogged=true]
data merge block 2064 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2067 100 2088 minecraft:barrier
setblock 2069 100 2088 minecraft:barrier
setblock 2068 100 2087 minecraft:barrier
setblock 2068 100 2089 minecraft:barrier
setblock 2068 100 2088 botanypots:white_concrete_botany_pot[facing=east,level=4,waterlogged=true]
data merge block 2068 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2071 100 2088 minecraft:barrier
setblock 2073 100 2088 minecraft:barrier
setblock 2072 100 2087 minecraft:barrier
setblock 2072 100 2089 minecraft:barrier
setblock 2072 100 2088 botanypots:white_concrete_hopper_botany_pot[facing=north,level=4,waterlogged=true]
data merge block 2072 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2075 100 2088 minecraft:barrier
setblock 2077 100 2088 minecraft:barrier
setblock 2076 100 2087 minecraft:barrier
setblock 2076 100 2089 minecraft:barrier
setblock 2076 100 2088 botanypots:white_concrete_waxed_botany_pot[facing=west,level=4,waterlogged=true]
data merge block 2076 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2080 100 2088 botanypots:white_glazed_terracotta_botany_pot[facing=south,level=5,waterlogged=false]
data merge block 2080 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2084 100 2088 botanypots:white_glazed_terracotta_hopper_botany_pot[facing=east,level=5,waterlogged=false]
data merge block 2084 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2088 100 2088 botanypots:white_glazed_terracotta_waxed_botany_pot[facing=north,level=5,waterlogged=false]
data merge block 2088 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2092 100 2088 botanypots:white_terracotta_botany_pot[facing=west,level=5,waterlogged=false]
data merge block 2092 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2095 100 2088 minecraft:barrier
setblock 2097 100 2088 minecraft:barrier
setblock 2096 100 2087 minecraft:barrier
setblock 2096 100 2089 minecraft:barrier
setblock 2096 100 2088 botanypots:white_terracotta_hopper_botany_pot[facing=south,level=5,waterlogged=true]
data merge block 2096 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2099 100 2088 minecraft:barrier
setblock 2101 100 2088 minecraft:barrier
setblock 2100 100 2087 minecraft:barrier
setblock 2100 100 2089 minecraft:barrier
setblock 2100 100 2088 botanypots:white_terracotta_waxed_botany_pot[facing=east,level=5,waterlogged=true]
data merge block 2100 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2103 100 2088 minecraft:barrier
setblock 2105 100 2088 minecraft:barrier
setblock 2104 100 2087 minecraft:barrier
setblock 2104 100 2089 minecraft:barrier
setblock 2104 100 2088 botanypots:yellow_concrete_botany_pot[facing=north,level=5,waterlogged=true]
data merge block 2104 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2107 100 2088 minecraft:barrier
setblock 2109 100 2088 minecraft:barrier
setblock 2108 100 2087 minecraft:barrier
setblock 2108 100 2089 minecraft:barrier
setblock 2108 100 2088 botanypots:yellow_concrete_hopper_botany_pot[facing=west,level=5,waterlogged=true]
data merge block 2108 100 2088 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2048 100 2092 botanypots:yellow_concrete_waxed_botany_pot[facing=south,level=6,waterlogged=false]
data merge block 2048 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2052 100 2092 botanypots:yellow_glazed_terracotta_botany_pot[facing=east,level=6,waterlogged=false]
data merge block 2052 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2056 100 2092 botanypots:yellow_glazed_terracotta_hopper_botany_pot[facing=north,level=6,waterlogged=false]
data merge block 2056 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2060 100 2092 botanypots:yellow_glazed_terracotta_waxed_botany_pot[facing=west,level=6,waterlogged=false]
data merge block 2060 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2063 100 2092 minecraft:barrier
setblock 2065 100 2092 minecraft:barrier
setblock 2064 100 2091 minecraft:barrier
setblock 2064 100 2093 minecraft:barrier
setblock 2064 100 2092 botanypots:yellow_terracotta_botany_pot[facing=south,level=6,waterlogged=true]
data merge block 2064 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2067 100 2092 minecraft:barrier
setblock 2069 100 2092 minecraft:barrier
setblock 2068 100 2091 minecraft:barrier
setblock 2068 100 2093 minecraft:barrier
setblock 2068 100 2092 botanypots:yellow_terracotta_hopper_botany_pot[facing=east,level=6,waterlogged=true]
data merge block 2068 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2071 100 2092 minecraft:barrier
setblock 2073 100 2092 minecraft:barrier
setblock 2072 100 2091 minecraft:barrier
setblock 2072 100 2093 minecraft:barrier
setblock 2072 100 2092 botanypots:yellow_terracotta_waxed_botany_pot[facing=north,level=6,waterlogged=true]
data merge block 2072 100 2092 {Items:[]}
scoreboard players add #shells botany_gallery 1
setblock 2075 100 2092 minecraft:barrier
setblock 2077 100 2092 minecraft:barrier
setblock 2076 100 2091 minecraft:barrier
setblock 2076 100 2093 minecraft:barrier
setblock 2076 100 2092 botanypots:terracotta_botany_pot[facing=west,level=6,waterlogged=true]
data merge block 2076 100 2092 {Items:[{Slot:0b,id:"minecraft:dirt",count:1},{Slot:1b,id:"minecraft:wheat_seeds",count:1}]}
scoreboard players add #representatives botany_gallery 1
setblock 2080 100 2092 botanypots:terracotta_hopper_botany_pot[facing=south,level=7,waterlogged=false]
data merge block 2080 100 2092 {Items:[{Slot:0b,id:"minecraft:dirt",count:1},{Slot:1b,id:"minecraft:wheat_seeds",count:1}]}
scoreboard players add #representatives botany_gallery 1
setblock 2084 100 2092 botanypots:terracotta_waxed_botany_pot[facing=east,level=7,waterlogged=false]
data merge block 2084 100 2092 {Items:[{Slot:0b,id:"minecraft:dirt",count:1},{Slot:1b,id:"minecraft:wheat_seeds",count:1}]}
scoreboard players add #representatives botany_gallery 1
setblock 2088 100 2092 botanypots:terracotta_botany_pot[facing=north,level=7,waterlogged=false]
data merge block 2088 100 2092 {Items:[{Slot:0b,id:"minecraft:sand",count:1},{Slot:1b,id:"minecraft:cactus",count:1}]}
scoreboard players add #representatives botany_gallery 1
setblock 2092 100 2092 botanypots:terracotta_hopper_botany_pot[facing=west,level=7,waterlogged=false]
data merge block 2092 100 2092 {Items:[{Slot:0b,id:"minecraft:sand",count:1},{Slot:1b,id:"minecraft:cactus",count:1}]}
scoreboard players add #representatives botany_gallery 1
setblock 2095 100 2092 minecraft:barrier
setblock 2097 100 2092 minecraft:barrier
setblock 2096 100 2091 minecraft:barrier
setblock 2096 100 2093 minecraft:barrier
setblock 2096 100 2092 botanypots:terracotta_waxed_botany_pot[facing=south,level=7,waterlogged=true]
data merge block 2096 100 2092 {Items:[{Slot:0b,id:"minecraft:sand",count:1},{Slot:1b,id:"minecraft:cactus",count:1}]}
scoreboard players add #representatives botany_gallery 1
setblock 2099 100 2092 minecraft:barrier
setblock 2101 100 2092 minecraft:barrier
setblock 2100 100 2091 minecraft:barrier
setblock 2100 100 2093 minecraft:barrier
setblock 2100 100 2092 botanypots:terracotta_botany_pot[facing=east,level=7,waterlogged=true]
data merge block 2100 100 2092 {Items:[]}
scoreboard players add #fallbacks botany_gallery 1
setblock 2103 100 2092 minecraft:barrier
setblock 2105 100 2092 minecraft:barrier
setblock 2104 100 2091 minecraft:barrier
setblock 2104 100 2093 minecraft:barrier
setblock 2104 100 2092 botanypots:terracotta_hopper_botany_pot[facing=north,level=7,waterlogged=true]
data merge block 2104 100 2092 {Items:[{Slot:0b,id:"minecraft:dirt",count:1},{Slot:1b,id:"minecraft:stick",count:1}]}
scoreboard players add #fallbacks botany_gallery 1
setblock 2107 100 2092 minecraft:barrier
setblock 2109 100 2092 minecraft:barrier
setblock 2108 100 2091 minecraft:barrier
setblock 2108 100 2093 minecraft:barrier
setblock 2108 100 2092 botanypots:terracotta_waxed_botany_pot[facing=west,level=7,waterlogged=true]
data merge block 2108 100 2092 {Items:[{Slot:0b,id:"minecraft:dirt",count:1},{Slot:1b,id:"minecraft:cactus",count:1}]}
scoreboard players add #fallbacks botany_gallery 1
