# Generated by gallery/generate.py; do not edit.
execute unless block 2048 100 2048 botanypots:black_concrete_botany_pot[facing=south,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2048 botanypots:black_concrete_hopper_botany_pot[facing=east,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2048 botanypots:black_concrete_waxed_botany_pot[facing=north,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2048 botanypots:black_glazed_terracotta_botany_pot[facing=west,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2048 botanypots:black_glazed_terracotta_hopper_botany_pot[facing=south,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2048 botanypots:black_glazed_terracotta_waxed_botany_pot[facing=east,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2048 botanypots:black_terracotta_botany_pot[facing=north,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2048 botanypots:black_terracotta_hopper_botany_pot[facing=west,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2048 botanypots:black_terracotta_waxed_botany_pot[facing=south,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2048 botanypots:blue_concrete_botany_pot[facing=east,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2048 botanypots:blue_concrete_hopper_botany_pot[facing=north,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2048 botanypots:blue_concrete_waxed_botany_pot[facing=west,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2048 botanypots:blue_glazed_terracotta_botany_pot[facing=south,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2048 botanypots:blue_glazed_terracotta_hopper_botany_pot[facing=east,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2048 botanypots:blue_glazed_terracotta_waxed_botany_pot[facing=north,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2048 botanypots:blue_terracotta_botany_pot[facing=west,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2052 botanypots:blue_terracotta_hopper_botany_pot[facing=south,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2052 botanypots:blue_terracotta_waxed_botany_pot[facing=east,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2052 botanypots:bricks_botany_pot[facing=north,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2052 botanypots:bricks_hopper_botany_pot[facing=west,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2052 botanypots:bricks_waxed_botany_pot[facing=south,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2052 botanypots:brown_concrete_botany_pot[facing=east,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2052 botanypots:brown_concrete_hopper_botany_pot[facing=north,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2052 botanypots:brown_concrete_waxed_botany_pot[facing=west,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2052 botanypots:brown_glazed_terracotta_botany_pot[facing=south,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2052 botanypots:brown_glazed_terracotta_hopper_botany_pot[facing=east,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2052 botanypots:brown_glazed_terracotta_waxed_botany_pot[facing=north,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2052 botanypots:brown_terracotta_botany_pot[facing=west,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2052 botanypots:brown_terracotta_hopper_botany_pot[facing=south,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2052 botanypots:brown_terracotta_waxed_botany_pot[facing=east,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2052 botanypots:cyan_concrete_botany_pot[facing=north,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2052 botanypots:cyan_concrete_hopper_botany_pot[facing=west,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2056 botanypots:cyan_concrete_waxed_botany_pot[facing=south,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2056 botanypots:cyan_glazed_terracotta_botany_pot[facing=east,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2056 botanypots:cyan_glazed_terracotta_hopper_botany_pot[facing=north,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2056 botanypots:cyan_glazed_terracotta_waxed_botany_pot[facing=west,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2056 botanypots:cyan_terracotta_botany_pot[facing=south,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2056 botanypots:cyan_terracotta_hopper_botany_pot[facing=east,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2056 botanypots:cyan_terracotta_waxed_botany_pot[facing=north,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2056 botanypots:deepslate_bricks_botany_pot[facing=west,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2056 botanypots:deepslate_bricks_hopper_botany_pot[facing=south,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2056 botanypots:deepslate_bricks_waxed_botany_pot[facing=east,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2056 botanypots:end_stone_bricks_botany_pot[facing=north,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2056 botanypots:end_stone_bricks_hopper_botany_pot[facing=west,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2056 botanypots:end_stone_bricks_waxed_botany_pot[facing=south,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2056 botanypots:gray_concrete_botany_pot[facing=east,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2056 botanypots:gray_concrete_hopper_botany_pot[facing=north,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2056 botanypots:gray_concrete_waxed_botany_pot[facing=west,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
