# Generated by gallery/generate.py; do not edit.
execute unless block 2048 100 2084 botanypots:red_concrete_botany_pot[facing=south,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2084 botanypots:red_concrete_hopper_botany_pot[facing=east,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2084 botanypots:red_concrete_waxed_botany_pot[facing=north,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2084 botanypots:red_glazed_terracotta_botany_pot[facing=west,level=2,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2084 botanypots:red_glazed_terracotta_hopper_botany_pot[facing=south,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2084 botanypots:red_glazed_terracotta_waxed_botany_pot[facing=east,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2084 botanypots:red_nether_bricks_botany_pot[facing=north,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2084 botanypots:red_nether_bricks_hopper_botany_pot[facing=west,level=2,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2084 botanypots:red_nether_bricks_waxed_botany_pot[facing=south,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2084 botanypots:red_terracotta_botany_pot[facing=east,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2084 botanypots:red_terracotta_hopper_botany_pot[facing=north,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2084 botanypots:red_terracotta_waxed_botany_pot[facing=west,level=3,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2084 botanypots:stone_bricks_botany_pot[facing=south,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2084 botanypots:stone_bricks_hopper_botany_pot[facing=east,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2084 botanypots:stone_bricks_waxed_botany_pot[facing=north,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2084 botanypots:terracotta_botany_pot[facing=west,level=3,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2088 botanypots:terracotta_hopper_botany_pot[facing=south,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2088 botanypots:terracotta_waxed_botany_pot[facing=east,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2088 botanypots:tuff_bricks_botany_pot[facing=north,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2088 botanypots:tuff_bricks_hopper_botany_pot[facing=west,level=4,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2088 botanypots:tuff_bricks_waxed_botany_pot[facing=south,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2088 botanypots:white_concrete_botany_pot[facing=east,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2088 botanypots:white_concrete_hopper_botany_pot[facing=north,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2088 botanypots:white_concrete_waxed_botany_pot[facing=west,level=4,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2088 botanypots:white_glazed_terracotta_botany_pot[facing=south,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2088 botanypots:white_glazed_terracotta_hopper_botany_pot[facing=east,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2088 botanypots:white_glazed_terracotta_waxed_botany_pot[facing=north,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2088 botanypots:white_terracotta_botany_pot[facing=west,level=5,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2088 botanypots:white_terracotta_hopper_botany_pot[facing=south,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2088 botanypots:white_terracotta_waxed_botany_pot[facing=east,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2088 botanypots:yellow_concrete_botany_pot[facing=north,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2088 botanypots:yellow_concrete_hopper_botany_pot[facing=west,level=5,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2092 botanypots:yellow_concrete_waxed_botany_pot[facing=south,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2092 botanypots:yellow_glazed_terracotta_botany_pot[facing=east,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2092 botanypots:yellow_glazed_terracotta_hopper_botany_pot[facing=north,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2092 botanypots:yellow_glazed_terracotta_waxed_botany_pot[facing=west,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2092 botanypots:yellow_terracotta_botany_pot[facing=south,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2092 botanypots:yellow_terracotta_hopper_botany_pot[facing=east,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2092 botanypots:yellow_terracotta_waxed_botany_pot[facing=north,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2092 botanypots:terracotta_botany_pot[facing=west,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
execute unless data block 2076 100 2092 Items[{Slot:0b,id:"minecraft:dirt"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2076 100 2092 Items[{Slot:1b,id:"minecraft:wheat_seeds"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2092 botanypots:terracotta_hopper_botany_pot[facing=south,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
execute unless data block 2080 100 2092 Items[{Slot:0b,id:"minecraft:dirt"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2080 100 2092 Items[{Slot:1b,id:"minecraft:wheat_seeds"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2092 botanypots:terracotta_waxed_botany_pot[facing=east,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
execute unless data block 2084 100 2092 Items[{Slot:0b,id:"minecraft:dirt"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2084 100 2092 Items[{Slot:1b,id:"minecraft:wheat_seeds"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2092 botanypots:terracotta_botany_pot[facing=north,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
execute unless data block 2088 100 2092 Items[{Slot:0b,id:"minecraft:sand"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2088 100 2092 Items[{Slot:1b,id:"minecraft:cactus"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2092 botanypots:terracotta_hopper_botany_pot[facing=west,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
execute unless data block 2092 100 2092 Items[{Slot:0b,id:"minecraft:sand"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2092 100 2092 Items[{Slot:1b,id:"minecraft:cactus"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2092 botanypots:terracotta_waxed_botany_pot[facing=south,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
execute unless data block 2096 100 2092 Items[{Slot:0b,id:"minecraft:sand"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2096 100 2092 Items[{Slot:1b,id:"minecraft:cactus"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2092 botanypots:terracotta_botany_pot[facing=east,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2092 botanypots:terracotta_hopper_botany_pot[facing=north,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
execute unless data block 2104 100 2092 Items[{Slot:0b,id:"minecraft:dirt"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2104 100 2092 Items[{Slot:1b,id:"minecraft:stick"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2092 botanypots:terracotta_waxed_botany_pot[facing=west,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
execute unless data block 2108 100 2092 Items[{Slot:0b,id:"minecraft:dirt"}] run scoreboard players add #failures botany_gallery 1
execute unless data block 2108 100 2092 Items[{Slot:1b,id:"minecraft:cactus"}] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
