# Generated by gallery/generate.py; do not edit.
execute unless block 2048 100 2060 botanypots:gray_glazed_terracotta_botany_pot[facing=south,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2060 botanypots:gray_glazed_terracotta_hopper_botany_pot[facing=east,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2060 botanypots:gray_glazed_terracotta_waxed_botany_pot[facing=north,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2060 botanypots:gray_terracotta_botany_pot[facing=west,level=6,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2060 botanypots:gray_terracotta_hopper_botany_pot[facing=south,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2060 botanypots:gray_terracotta_waxed_botany_pot[facing=east,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2060 botanypots:green_concrete_botany_pot[facing=north,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2060 botanypots:green_concrete_hopper_botany_pot[facing=west,level=6,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2060 botanypots:green_concrete_waxed_botany_pot[facing=south,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2060 botanypots:green_glazed_terracotta_botany_pot[facing=east,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2060 botanypots:green_glazed_terracotta_hopper_botany_pot[facing=north,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2060 botanypots:green_glazed_terracotta_waxed_botany_pot[facing=west,level=7,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2060 botanypots:green_terracotta_botany_pot[facing=south,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2060 botanypots:green_terracotta_hopper_botany_pot[facing=east,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2060 botanypots:green_terracotta_waxed_botany_pot[facing=north,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2060 botanypots:light_blue_concrete_botany_pot[facing=west,level=7,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2064 botanypots:light_blue_concrete_hopper_botany_pot[facing=south,level=8,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2064 botanypots:light_blue_concrete_waxed_botany_pot[facing=east,level=8,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2064 botanypots:light_blue_glazed_terracotta_botany_pot[facing=north,level=8,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2064 botanypots:light_blue_glazed_terracotta_hopper_botany_pot[facing=west,level=8,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2064 botanypots:light_blue_glazed_terracotta_waxed_botany_pot[facing=south,level=8,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2064 botanypots:light_blue_terracotta_botany_pot[facing=east,level=8,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2064 botanypots:light_blue_terracotta_hopper_botany_pot[facing=north,level=8,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2064 botanypots:light_blue_terracotta_waxed_botany_pot[facing=west,level=8,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2064 botanypots:light_gray_concrete_botany_pot[facing=south,level=9,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2064 botanypots:light_gray_concrete_hopper_botany_pot[facing=east,level=9,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2064 botanypots:light_gray_concrete_waxed_botany_pot[facing=north,level=9,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2064 botanypots:light_gray_glazed_terracotta_botany_pot[facing=west,level=9,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2064 botanypots:light_gray_glazed_terracotta_hopper_botany_pot[facing=south,level=9,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2064 botanypots:light_gray_glazed_terracotta_waxed_botany_pot[facing=east,level=9,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2064 botanypots:light_gray_terracotta_botany_pot[facing=north,level=9,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2064 botanypots:light_gray_terracotta_hopper_botany_pot[facing=west,level=9,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2068 botanypots:light_gray_terracotta_waxed_botany_pot[facing=south,level=10,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2068 botanypots:lime_concrete_botany_pot[facing=east,level=10,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2068 botanypots:lime_concrete_hopper_botany_pot[facing=north,level=10,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2068 botanypots:lime_concrete_waxed_botany_pot[facing=west,level=10,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2068 botanypots:lime_glazed_terracotta_botany_pot[facing=south,level=10,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2068 botanypots:lime_glazed_terracotta_hopper_botany_pot[facing=east,level=10,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2068 botanypots:lime_glazed_terracotta_waxed_botany_pot[facing=north,level=10,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2068 botanypots:lime_terracotta_botany_pot[facing=west,level=10,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2068 botanypots:lime_terracotta_hopper_botany_pot[facing=south,level=11,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2068 botanypots:lime_terracotta_waxed_botany_pot[facing=east,level=11,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2068 botanypots:magenta_concrete_botany_pot[facing=north,level=11,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2068 botanypots:magenta_concrete_hopper_botany_pot[facing=west,level=11,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2068 botanypots:magenta_concrete_waxed_botany_pot[facing=south,level=11,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2068 botanypots:magenta_glazed_terracotta_botany_pot[facing=east,level=11,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2068 botanypots:magenta_glazed_terracotta_hopper_botany_pot[facing=north,level=11,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2068 botanypots:magenta_glazed_terracotta_waxed_botany_pot[facing=west,level=11,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
