# Generated by gallery/generate.py; do not edit.
execute unless block 2048 100 2072 botanypots:magenta_terracotta_botany_pot[facing=south,level=12,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2072 botanypots:magenta_terracotta_hopper_botany_pot[facing=east,level=12,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2072 botanypots:magenta_terracotta_waxed_botany_pot[facing=north,level=12,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2072 botanypots:mossy_stone_bricks_botany_pot[facing=west,level=12,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2072 botanypots:mossy_stone_bricks_hopper_botany_pot[facing=south,level=12,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2072 botanypots:mossy_stone_bricks_waxed_botany_pot[facing=east,level=12,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2072 botanypots:mud_bricks_botany_pot[facing=north,level=12,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2072 botanypots:mud_bricks_hopper_botany_pot[facing=west,level=12,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2072 botanypots:mud_bricks_waxed_botany_pot[facing=south,level=13,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2072 botanypots:nether_bricks_botany_pot[facing=east,level=13,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2072 botanypots:nether_bricks_hopper_botany_pot[facing=north,level=13,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2072 botanypots:nether_bricks_waxed_botany_pot[facing=west,level=13,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2072 botanypots:orange_concrete_botany_pot[facing=south,level=13,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2072 botanypots:orange_concrete_hopper_botany_pot[facing=east,level=13,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2072 botanypots:orange_concrete_waxed_botany_pot[facing=north,level=13,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2072 botanypots:orange_glazed_terracotta_botany_pot[facing=west,level=13,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2076 botanypots:orange_glazed_terracotta_hopper_botany_pot[facing=south,level=14,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2076 botanypots:orange_glazed_terracotta_waxed_botany_pot[facing=east,level=14,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2076 botanypots:orange_terracotta_botany_pot[facing=north,level=14,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2076 botanypots:orange_terracotta_hopper_botany_pot[facing=west,level=14,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2076 botanypots:orange_terracotta_waxed_botany_pot[facing=south,level=14,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2076 botanypots:pink_concrete_botany_pot[facing=east,level=14,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2076 botanypots:pink_concrete_hopper_botany_pot[facing=north,level=14,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2076 botanypots:pink_concrete_waxed_botany_pot[facing=west,level=14,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2076 botanypots:pink_glazed_terracotta_botany_pot[facing=south,level=15,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2076 botanypots:pink_glazed_terracotta_hopper_botany_pot[facing=east,level=15,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2076 botanypots:pink_glazed_terracotta_waxed_botany_pot[facing=north,level=15,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2076 botanypots:pink_terracotta_botany_pot[facing=west,level=15,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2076 botanypots:pink_terracotta_hopper_botany_pot[facing=south,level=15,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2076 botanypots:pink_terracotta_waxed_botany_pot[facing=east,level=15,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2076 botanypots:polished_blackstone_bricks_botany_pot[facing=north,level=15,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2076 botanypots:polished_blackstone_bricks_hopper_botany_pot[facing=west,level=15,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2048 100 2080 botanypots:polished_blackstone_bricks_waxed_botany_pot[facing=south,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2052 100 2080 botanypots:prismarine_bricks_botany_pot[facing=east,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2056 100 2080 botanypots:prismarine_bricks_hopper_botany_pot[facing=north,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2060 100 2080 botanypots:prismarine_bricks_waxed_botany_pot[facing=west,level=0,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2064 100 2080 botanypots:purple_concrete_botany_pot[facing=south,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2068 100 2080 botanypots:purple_concrete_hopper_botany_pot[facing=east,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2072 100 2080 botanypots:purple_concrete_waxed_botany_pot[facing=north,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2076 100 2080 botanypots:purple_glazed_terracotta_botany_pot[facing=west,level=0,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2080 100 2080 botanypots:purple_glazed_terracotta_hopper_botany_pot[facing=south,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2084 100 2080 botanypots:purple_glazed_terracotta_waxed_botany_pot[facing=east,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2088 100 2080 botanypots:purple_terracotta_botany_pot[facing=north,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2092 100 2080 botanypots:purple_terracotta_hopper_botany_pot[facing=west,level=1,waterlogged=false] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2096 100 2080 botanypots:purple_terracotta_waxed_botany_pot[facing=south,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2100 100 2080 botanypots:quartz_bricks_botany_pot[facing=east,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2104 100 2080 botanypots:quartz_bricks_hopper_botany_pot[facing=north,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
execute unless block 2108 100 2080 botanypots:quartz_bricks_waxed_botany_pot[facing=west,level=1,waterlogged=true] run scoreboard players add #failures botany_gallery 1
scoreboard players add #checked botany_gallery 1
